# Generated by Django 4.2.3 on 2023-07-23 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0002_item_item_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="item_image",
            field=models.ImageField(default="", upload_to="food/images"),
        ),
    ]
