# Generated by Django 4.2.3 on 2023-07-23 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0003_alter_item_item_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="item_discountOffer",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AddField(
            model_name="item",
            name="item_shopAddress",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AddField(
            model_name="item",
            name="item_shopName",
            field=models.CharField(default="", max_length=200),
        ),
    ]
