# Generated by Django 4.2.3 on 2023-07-23 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0004_item_item_discountoffer_item_item_shopaddress_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="item_userRole",
            field=models.CharField(default="", max_length=200),
        ),
    ]
